In [1]:
####NumPy++ Numeric Python.....

In [2]:
###it is design to Handle Numeric Values

In [3]:
###Numpy Has Multidimenssional Data 1D,2D,3D,4D

In [4]:
##1D---Only row Or Column

In [5]:
##2D--- Combination Row And Column

In [6]:
## There are index in numpy Data also .... Positive index and negetive index

In [7]:
#X[row,column]==there are first awlway rows and second always column

In [8]:
import numpy as np

In [11]:
data=np.random.randint(0,10) ##here we get ranndom value in bet 1to 9 ... every time we get new random value

In [12]:
data

0

In [14]:
data=np.random.randint(0,10,5)

In [16]:
data ##here we get random 5 values in single row


array([3, 9, 3, 6, 0], dtype=int32)

In [17]:
data=np.random.randint(0,10,(5,5))

In [19]:
data ## here we get rand values for 5row and 5 collumn...

array([[3, 8, 7, 5, 1],
       [0, 3, 2, 0, 0],
       [2, 3, 1, 1, 6],
       [3, 4, 4, 0, 2],
       [9, 9, 2, 0, 6]], dtype=int32)

In [ ]:
###  now for how to access data in 

In [21]:
data[0,0]


np.int32(3)

In [23]:
data[2,3]

np.int32(1)

In [22]:
data[-3:-1,-3:-1]

array([[1, 1],
       [4, 0]], dtype=int32)

In [24]:
data[-4:-2,-3:-1]

array([[2, 0],
       [1, 1]], dtype=int32)

In [28]:
"""
Difference between List And Array
1. List=if we have to do an operation with list it dose not allow it .. we ave do it element by elelment ot we have to use if...
  Array=it allows us do an operay over array in single attempt
2. List= list can keep data as same as which type of data is
   Arrays=list can covert whole data in sinle data type which is suitable
3. List=Heterogenious : it can contain all data types..
   Arrays= it conert data in single data type
"""

# """ Shubham Sarade""": Doc strings

'\nDifference between List And Array\n1. List=if we have to do an operation with list it dose not allow it .. we ave do it element by elelment ot we have to use if...\n  Array=it allows us do an operay over array in single attempt\n2. List= list can keep data as same as which type of data is\n   Arrays=list can covert whole data in sinle data type which is suitable\n3. List=Heterogenious : it can contain all data types..\n   Arrays= it conert data in single data type\n'

In [2]:
import numpy as np


In [1]:
##Functions of ***Random Family Function***

In [ ]:
####RAndint

In [3]:
np.random.randint(0,100)

10

In [4]:
np.random.randint(0,100,5)

array([74, 82, 66, 90, 54], dtype=int32)

In [5]:
np.random.randint(0,100,(10,10))

array([[91, 36, 78,  3, 42,  5, 73, 98, 55, 19],
       [27, 51, 80, 73, 21, 85, 35, 58, 91, 98],
       [39, 86,  4, 89, 97, 82, 24, 53, 32, 79],
       [71, 68, 11, 64, 79, 83, 12, 47,  8, 71],
       [84,  5,  5, 35, 48, 41, 59, 81,  7, 99],
       [25, 41, 76, 61, 35, 48, 77, 27, 86, 50],
       [55, 72, 17,  7, 83, 46, 31, 66, 70, 60],
       [95, 77, 46, 96, 88, 30, 62, 33, 76, 16],
       [ 4, 84, 64, 25, 16, 71, 77, 10,  7, 60],
       [94, 39, 15, 94, 20, 81, 53, 50, 32, 36]], dtype=int32)

In [6]:
###Rand

In [9]:
np.random.rand(12) ### in this function we ger random vallues in bet 0.00 to 0.9

array([0.33829532, 0.69892056, 0.47488113, 0.0638585 , 0.72887525,
       0.31527296, 0.59294045, 0.57686634, 0.1930357 , 0.18209401,
       0.02159469, 0.90477744])

In [11]:
np.random.rand(3,3) # it gives 3 row and 3 collumn

array([[0.79397985, 0.0619814 , 0.11392009],
       [0.69071095, 0.7351332 , 0.48661908],
       [0.81777636, 0.56759874, 0.39785392]])