In [14]:
## linear algebra
   ## scalars

x = 5
y = 10.5
z = -3.2


In [15]:
## vectors
v = [1, 2, 3]

In [16]:
## vectors in numpy 
import numpy as np

v = np.array([1, 2, 3])

print(v)

[1 2 3]


In [17]:
## matrices
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

print(A)

[[1 2]
 [3 4]]


In [18]:
X = [
    [21, 20000],
    [25, 30000]
]

In [19]:
## matrix shape
A = np.array([
    [1,2,3],
    [4,5,6]
])
print(A.shape)

(2, 3)


In [20]:
## matrix addition
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A + B)

[[ 6  8]
 [10 12]]


In [21]:
## matrix multiplication
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(A @ B)

[[19 22]
 [43 50]]


In [22]:
## dot product
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


In [23]:
## transpose
A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
## dererminant
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.det(A))

-2.0000000000000004


In [25]:
## matrix inverse
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
## eigenvalues and eigenvectors
A = np.array([
    [4,2],
    [1,3]
])

values, vectors = np.linalg.eig(A)

print(values)
print(vectors)

[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [27]:
## statistics

    ## mean 
import numpy as np

data = [10,20,30,40]

print(np.mean(data))

25.0


In [28]:
## median 
import numpy as np

data = [1,2,3,100]

print(np.median(data))

2.5


In [29]:
## mode 
from statistics import mode

data = [1,2,2,3,3,3,4]

print(mode(data))

3


In [30]:
## variance
import numpy as np

data = [10,20,30,40]

print(np.var(data))

125.0


In [31]:
## standard deviation
import numpy as np

data = [10,20,30,40]

print(np.std(data))

11.180339887498949


In [32]:
### correlation
import numpy as np

x = [1,2,3,4]
y = [2,4,6,8]

print(np.corrcoef(x,y))


[[1. 1.]
 [1. 1.]]
